# **10 minutes to pandas**
* https://pandas.pydata.org/docs/user_guide/10min.html#
* pip install numpy, pandas

In [2]:
import numpy as np
import pandas as pd

# **기본 구조**
* <font color=red><b>Series: 1차 데이터
* <font color=red><b>DataFrame: 2차 데이터 (like table)

<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*OaUbgSxKnC_kaRj0H6vK5Q.jpeg" widcth=400>
<pre>  단일값[0]   리스트,튜플,딕[1]    Series[1]      DataFrame[2]             Tensor[3]

# **C:생성**

In [6]:
mylist = [1, 3, 5, np.nan, 6, 8]
print(mylist)
s = pd.Series(mylist)
print(s)

[1, 3, 5, nan, 6, 8]
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [11]:
mylist =[ [1, 3, 5, np.nan, 6, 8],
          [1, 3, 5, np.nan, 6, 8],
          [1, 3, 5, np.nan, 6, 8]
        ]
df = pd.DataFrame(mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])
print(df)  

df

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

In [22]:
df.dtypes

a    int64
b    int64
c    int64
dtype: object

In [23]:
mydict = {"a":[1,1,1], "b":[3,3,3,], "c":[5,5,5]}
df1 = pd.DataFrame(mydict)
df1

   a  b  c
0  1  3  5
1  1  3  5
2  1  3  5

In [24]:
df1.dtypes

a    int64
b    int64
c    int64
dtype: object

In [15]:
mylist1= [5,6,10]
a = pd.Series(mylist1)
print(a)

0     5
1     6
2    10
dtype: int64

In [18]:
mydict1={"stt":[1,2,3], "name":["Linh","Lan","Min"],"age":[20,30,14]}
b = pd.DataFrame(mydict1)
print(b)

b

   stt  name  age
0    1  Linh   20
1    2   Lan   30
2    3   Min   14

   stt  name  age
0    1  Linh   20
1    2   Lan   30
2    3   Min   14

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [25]:
df.head()

   a  b  c
0  1  3  5
1  1  3  5
2  1  3  5