# **10 minutes to pandas**
* https://pandas.pydata.org/docs/user_guide/10min.html#
* pip install numpy, pandas

In [1]:
import numpy as np
import pandas as pd

# **기본 구조**
* <font color=red><b>Series: 1차 데이터
* <font color=red><b>DataFrame: 2차 데이터 (like table)

<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*OaUbgSxKnC_kaRj0H6vK5Q.jpeg" widcth=400>
<pre>  단일값[0]   리스트,튜플,딕[1]    Series[1]      DataFrame[2]             Tensor[3]

# **C:생성**

In [2]:
mylist = [1, 3, 5, np.nan, 6, 8]
print(mylist)
s = pd.Series(mylist)
print(s)

[1, 3, 5, nan, 6, 8]
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
mylist =[ [1, 3, 5, np.nan, 6, 8],
          [1, 3, 5, np.nan, 6, 8],
          [1, 3, 5, np.nan, 6, 8]
        ]
df = pd.DataFrame(mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])
print(df)  

df

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

In [4]:
upyterdf.dtypes

a      int64
b      int64
c      int64
d    float64
e      int64
f      int64
dtype: object

In [5]:
mydict = {"a":[1,1,1], "b":[3,3,3,], "c":[5,5,5]}
df1 = pd.DataFrame(mydict)
df1

   a  b  c
0  1  3  5
1  1  3  5
2  1  3  5

In [6]:
df1.dtypes

a    int64
b    int64
c    int64
dtype: object

In [7]:
mylist1= [5,6,10]
a = pd.Series(mylist1)
print(a)

0     5
1     6
2    10
dtype: int64

In [8]:
mydict1={"stt":[1,2,3], "name":["Linh","Lan","Min"],"age":[20,30,14]}
b = pd.DataFrame(mydict1)
print(b)

b

   stt  name  age
0    1  Linh   20
1    2   Lan   30
2    3   Min   14

   stt  name  age
0    1  Linh   20
1    2   Lan   30
2    3   Min   14

In [9]:
df.head()

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

# **viewing data**
* <font color=red><b>df.info() </b></font>
* df.shape : 행*열
* df.index : 인덱스
* df.columns : 컬럼이름
* df.head() / df.tail()

https://www.kaggle.com/datasets/arunjathari/bostonhousepricedata

<pre>
| **CRIM**    | 범죄율         | 지역별 1인당 범죄율                  |
| **ZN**      | 주거지역 비율     | 25,000 sq.ft 초과 주거용 토지 비율    |
| **INDUS**   | 비소매 상업지역 비율 | 비소매업 용도의 토지 비율               |
| **CHAS**    | 찰스강 인접 여부   | 찰스강에 접하면 **1**, 아니면 **0**    |
| **NOX**     | 일산화질소 농도    | 대기오염 정도를 나타내는 질소산화물 농도       |
| **RM**      | 평균 방 개수     | 주택 한 채당 평균 방(Room) 수         |
| **AGE**     | 오래된 주택 비율   | 1940년 이전에 지어진 주택 비율          |
| **DIS**     | 고용센터까지 거리   | 보스턴의 주요 고용센터 5곳까지의 가중 거리     |
| **RAD**     | 고속도로 접근성    | 방사형 고속도로 접근성 지수              |
| **TAX**     | 재산세율        | $10,000당 재산세율                |
| **PTRATIO** | 학생/교사 비율    | 지역별 학생 대 교사 비율               |
| **B**       | 인구 관련 변수    | 원본 데이터에서 흑인 인구 비율을 변환해 만든 변수 |
| **LSTAT**   | 저소득층 비율     | 낮은 사회경제적 지위 인구의 비율(%)        |
| **MEDV**    | 주택가격        | 주택가격 중앙값, 단위는 **$1,000**     |

In [10]:
df = pd.read_csv("../datas/Boston-house-price-data.csv")
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [11]:
df.shape

(506, 14)

In [12]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [14]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [15]:
df.head(30)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9
10,0.22489,12.5,7.87,0,0.524,6.377,94.3,6.3467,5,311.0,15.2,392.52,20.45,15.0
11,0.11747,12.5,7.87,0,0.524,6.009,82.9,6.2267,5,311.0,15.2,396.90,13.27,18.9
12,0.09378,12.5,7.87,0,0.524,5.889,39.0,5.4509,5,311.0,15.2,390.50,15.71,21.7
13,0.62976,0.0,8.14,0,0.538,5.949,61.8,4.7075,4,307.0,21.0,396.90,8.26,20.4
14,0.63796,0.0,8.14,0,0.538,6.096,84.5,4.4619,4,307.0,21.0,380.02,10.26,18.2
15,0.62739,0.0,8.14,0,0.538,5.834,56.5,4.4986,4,307.0,21.0,395.62,8.47,19.9
16,1.05393,0.0,8.14,0,0.538,5.935,29.3,4.4986,4,307.0,21.0,386.85,6.58,23.1
17,0.78420,0.0,8.14,0,0.538,5.990,81.7,4.2579,4,307.0,21.0,386.75,14.67,17.5
18,0.80271,0.0,8.14,0,0.538,5.456,36.6,3.7965,4,307.0,21.0,288.99,11.69,20.2
19,0.72580,0.0,8.14,0,0.538,5.727,69.5,3.7965,4,307.0,21.0,390.95,11.28,18.2
20,1.25179,0.0,8.14,0,0.538,5.570,98.1,3.7979,4,307.0,21.0,376.57,21.02,13.6
21,0.85204,0.0,8.14,0,0.538,5.965,89.2,4.0123,4,307.0,21.0,392.53,13.83,19.6
22,1.23247,0.0,8.14,0,0.538,6.142,91.7,3.9769,4,307.0,21.0,396.90,18.72,15.2
23,0.98843,0.0,8.14,0,0.538,5.813,100.0,4.0952,4,307.0,21.0,394.54,19.88,14.5
24,0.75026,0.0,8.14,0,0.538,5.924,94.1,4.3996,4,307.0,21.0,394.33,16.30,15.6
25,0.84054,0.0,8.14,0,0.538,5.599,85.7,4.4546,4,307.0,21.0,303.42,16.51,13.9
26,0.67191,0.0,8.14,0,0.538,5.813,90.3,4.6820,4,307.0,21.0,376.88,14.81,16.6
27,0.95577,0.0,8.14,0,0.538,6.047,88.8,4.4534,4,307.0,21.0,306.38,17.28,14.8
28,0.77299,0.0,8.14,0,0.538,6.495,94.4,4.4547,4,307.0,21.0,387.94,12.80,18.4
29,1.00245,0.0,8.14,0,0.538,6.674,87.3,4.2390,4,307.0,21.0,380.23,11.98,21.0

In [16]:
df.tail(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [17]:
df.index

RangeIndex(start=0, stop=506, step=1)

# **selection**
* []
* df.at() df.iat()
* *df.loc() dfiloc()

In [18]:
df = df[0:5].copy()

In [19]:
df.shape

(5, 14)

In [20]:
df["B"]

0    396.90
1    396.90
2    392.83
3    394.63
4    396.90
Name: B, dtype: float64

In [21]:
df["CRIM"]

0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
Name: CRIM, dtype: float64

In [22]:
df[["CRIM","B"]]

      CRIM       B
0  0.00632  396.90
1  0.02731  396.90
2  0.02729  392.83
3  0.03237  394.63
4  0.06905  396.90

* **슬라이싱**

In [23]:
df[0:2]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.9,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.9,9.14,21.6

In [24]:
df.iloc[0:2 , 0:3]

      CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07

In [25]:
df.iloc[2:5,2:5]

   INDUS  CHAS    NOX
2   7.07     0  0.469
3   2.18     0  0.458
4   2.18     0  0.458

In [26]:
df.loc[2:5,"INDUS":"NOX"]

   INDUS  CHAS    NOX
2   7.07     0  0.469
3   2.18     0  0.458
4   2.18     0  0.458

In [27]:
mylist =[ [1, 3, 5, np.nan, 6, 8],
          [1, 3, 5, np.nan, 6, 8],
          [1, 3, 5, np.nan, 6, 8]
        ]
df2 = pd.DataFrame(mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])
print(df2)  

df2

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

In [28]:
df2.loc[10:20, "c":"f"]

    c   d  e  f
10  5 NaN  6  8
20  5 NaN  6  8

In [29]:
df2.iloc[0:2,2:6 ]

    c   d  e  f
10  5 NaN  6  8
20  5 NaN  6  8

# **at/iat**

In [30]:
df.iat[0,1]

np.float64(18.0)

In [31]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [32]:
df.at[0,"ZN"]

np.float64(18.0)

In [33]:
df3 = pd.DataFrame( {"a":[1,2,3], "b":[10,20,30]} , index=[10,20,30])
print(df3.index)
print(  df3.loc[ 10:20 ,  "a"  ] )
df3

# df3 = pd.DataFrame( {"a":[1,2,3], "b":[10,20,30]} , index=['10','20','30'])
# print(df3.index)
# print( df3.loc[ '10':'20' ,  "a"  ]  )
# df3

Index([10, 20, 30], dtype='int64')
10    1
20    2
Name: a, dtype: int64

    a   b
10  1  10
20  2  20
30  3  30

In [34]:
 df3 = pd.DataFrame( {"a":[1,2,3], "b":[10,20,30]} , index=['10','20','30'])
 print(df3.index)
 print( df3.loc[ '10':'20' ,  "a"  ]  )
 df3

Index(['10', '20', '30'], dtype='str')
10    1
20    2
Name: a, dtype: int64

    a   b
10  1  10
20  2  20
30  3  30

In [35]:
df3 = pd.DataFrame( {"a":[1,2,3], "b":[10,20,30]} , index=['10','20','30'])
df3

    a   b
10  1  10
20  2  20
30  3  30

In [36]:
df3.loc['10':'20' , "a"]

10    1
20    2
Name: a, dtype: int64

In [37]:
df3.index

Index(['10', '20', '30'], dtype='str')

In [38]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [39]:
df.iloc[[0,2,4] , [0,1,2,-1]]

      CRIM    ZN  INDUS  MEDV
0  0.00632  18.0   2.31  24.0
2  0.02729   0.0   7.07  34.7
4  0.06905   0.0   2.18  36.2

In [40]:
df.loc[[0,2,4] , ["CRIM","ZN","INDUS","MEDV"]]

      CRIM    ZN  INDUS  MEDV
0  0.00632  18.0   2.31  24.0
2  0.02729   0.0   7.07  34.7
4  0.06905   0.0   2.18  36.2

# **Missing data**
* 겅즉 : NaN, null,np.nan
* <font color=red><b>fillna() : 채우기(보간)
* <font color=red><b>dropna() : 버리기
* <font color=red><b>isna() : 결측체크

In [41]:
mylist =[ [1, 3, 5, np.nan, 6, 8],
          [1, 3, 5, np.nan, 6, 8],
          [1, 3, 5, np.nan, 6, 8]
        ]
df2 = pd.DataFrame(mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])
print(df2)  


df2

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

In [42]:
df2['a'] + 10

10    11
20    11
30    11
Name: a, dtype: int64

* <font color=red><b>결측이 있는 'd' 컬럼은 어떠한 연산을 가해도 결측이다

In [43]:
df2['a'] + df2['b']

10    4
20    4
30    4
dtype: int64

In [44]:
df2['a'] + df2['d']

10   NaN
20   NaN
30   NaN
dtype: float64

In [45]:
df2.isna()

        a      b      c     d      e      f
10  False  False  False  True  False  False
20  False  False  False  True  False  False
30  False  False  False  True  False  False

In [46]:
df2.isna().sum()

a    0
b    0
c    0
d    3
e    0
f    0
dtype: int64

In [47]:
df2.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 10 to 30
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       0 non-null      float64
 4   e       3 non-null      int64
 5   f       3 non-null      int64
dtypes: float64(1), int64(5)
memory usage: 168.0 bytes

In [48]:
df2 = df2.fillna(0)
#df2 = df2.fillna(0,inplace=True)

In [49]:
df2

    a  b  c    d  e  f
10  1  3  5  0.0  6  8
20  1  3  5  0.0  6  8
30  1  3  5  0.0  6  8

In [50]:
df2 = df2.fillna(0)
df2

    a  b  c    d  e  f
10  1  3  5  0.0  6  8
20  1  3  5  0.0  6  8
30  1  3  5  0.0  6  8

## 결측 삭제
* <font color=red>df.dropna(axis=0) : 행(줄,가로,↓)지우기
* <font color=red>df.dropna(axis=1) : 열(칸,세로,→)지우기
* <font color=red>df.dropna(subset=['컬럼']) : 컬럼에 결측 지우기
* <font color=red>df.drop(columns=['컬럼']) : 컬럼 삭제

In [51]:
mylist =  [  [1, 3, 5, np.nan, 6, 8] ,
             [1, 3, np.nan, 5,  np.nan, 8] ,
             [1, 3, np.nan, 6, 6, 8],
             [1, 3, 5, 6, 6, 8],
          ]   
df2 = pd.DataFrame(mylist, index=[10,20,30,40], columns=['a','b','c','d','e','f'])
df33 = df2.copy()
df44 = df2.copy()
df55 = df2.copy()

* df.dropna(axis=0) : 행(줄,가로,↓)지우기

In [52]:
df33

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
20  1  3  NaN  5.0  NaN  8
30  1  3  NaN  6.0  6.0  8
40  1  3  5.0  6.0  6.0  8

In [53]:
 df33.dropna(axis=0)

    a  b    c    d    e  f
40  1  3  5.0  6.0  6.0  8

In [54]:
df33 = df33.dropna(axis=0)
df33

    a  b    c    d    e  f
40  1  3  5.0  6.0  6.0  8

In [55]:
df44

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
20  1  3  NaN  5.0  NaN  8
30  1  3  NaN  6.0  6.0  8
40  1  3  5.0  6.0  6.0  8

In [56]:
df44 = df44.dropna(axis=1)
df44

    a  b  f
10  1  3  8
20  1  3  8
30  1  3  8
40  1  3  8

In [57]:
df55

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
20  1  3  NaN  5.0  NaN  8
30  1  3  NaN  6.0  6.0  8
40  1  3  5.0  6.0  6.0  8

In [58]:
df55=df55.dropna(subset=['c'])

In [59]:
df55

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
40  1  3  5.0  6.0  6.0  8

In [60]:
df55 = df55.drop(columns=['a','b'])

In [64]:
df55

      c    d    e  f
10  5.0  NaN  6.0  8
40  5.0  6.0  6.0  8

# **stat**

In [65]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [ ]:
## value_counts()

# describe()

In [68]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,5.000000,5.000000,5.000000,5.0,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.032468,3.600000,4.162000,0.0,0.478400,6.865200,61.040000,5.229720,2.20000,244.800000,17.660000,395.632000,5.284000,29.980000
std,0.022778,8.049845,2.655159,0.0,0.033768,0.346716,12.402943,0.840081,0.83666,30.318311,1.393915,1.849235,2.346813,6.682963
min,0.006320,0.000000,2.180000,0.0,0.458000,6.421000,45.800000,4.090000,1.00000,222.000000,15.300000,392.830000,2.940000,21.600000
25%,0.027290,0.000000,2.180000,0.0,0.458000,6.575000,54.200000,4.967100,2.00000,222.000000,17.800000,394.630000,4.030000,24.000000
50%,0.027310,0.000000,2.310000,0.0,0.469000,6.998000,61.100000,4.967100,2.00000,242.000000,17.800000,396.900000,4.980000,33.400000
75%,0.032370,0.000000,7.070000,0.0,0.469000,7.147000,65.200000,6.062200,3.00000,242.000000,18.700000,396.900000,5.330000,34.700000
max,0.069050,18.000000,7.070000,0.0,0.538000,7.185000,78.900000,6.062200,3.00000,296.000000,18.700000,396.900000,9.140000,36.200000

# value_count()

In [69]:
df['RAD']

0    1
1    2
2    2
3    3
4    3
Name: RAD, dtype: int64

# str.함수()

In [71]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='str')

In [72]:
df.columns.str.lower()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='str')

# ***★★★Grouping*★★★**
* max(), min(), sum(), count(), std()

In [78]:
df77 = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)
df77.head(3)

     A  B    C         D         E
0  one  A  foo -0.530534 -1.562573
1  one  B  foo -0.785990 -0.181891
2  two  C  foo  0.056768  0.885296

In [80]:
df77.groupby("A")["D"].sum()

A
one      0.835856
three    2.700015
two      1.544764
Name: D, dtype: float64

In [81]:
df77.groupby("A")["D"].min()

A
one     -1.126547
three   -0.126838
two     -0.289895
Name: D, dtype: float64

In [82]:
df77.groupby("A")["D"].agg(['min','max'])

            min       max
A
one   -1.126547  1.940108
three -0.126838  1.863554
two   -0.289895  1.777891

In [83]:
df77.groupby("A").agg({"D":"min", "E":"max"})

              D         E
A
one   -1.126547  2.073956
three -0.126838 -0.561456
two   -0.289895  1.018594

# **merge vs. concat**

## concat(axis=)
* <font color=red><B>0 : 위(2) 아래(3)  = 총 5줄
* <font color=red><B>1 : 열(2) 열(3)    = 총5열

In [86]:
dfa = pd.DataFrame({"a" : [1,2,3] , "b":[10,20,30]})
dfb = pd.DataFrame({"a" : [4,5] , "b":[40,50]})

In [87]:
dfa

   a   b
0  1  10
1  2  20
2  3  30

In [88]:
dfb

   a   b
0  4  40
1  5  50

In [91]:
pd.concat([dfa, dfb], axis=0)

   a   b
0  1  10
1  2  20
2  3  30
0  4  40
1  5  50

In [97]:
dfab = pd.concat([dfa, dfb], axis=0)
dfab = dfab.reset_index(drop=True)
dfab

   a   b
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [95]:
dfab = pd.concat([dfa, dfb], axis=1)
dfab.columns = ['a','b', 'c','d']
dfab

   a   b    c     d
0  1  10  4.0  40.0
1  2  20  5.0  50.0
2  3  30  NaN   NaN

## **merge(on="columns",how=inner/outer)**
* <font color=red><B>0 : 위(2) 아래(3)  = 총 5줄
* <font color=red><B>1 : 열(2) 열(3)    = 총5열

In [98]:
dfab= dfa.merge(dfb, left_index=True, right_index=True, how='inner')
dfab

   a_x  b_x  a_y  b_y
0    1   10    4   40
1    2   20    5   50

In [105]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [106]:
left

   key  lval
0  foo     1
1  foo     2

In [107]:
right

   key  rval
0  foo     4
1  foo     5

In [111]:
dfab= left.merge(right,on='key', how='inner')
dfab

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [112]:
left = pd.DataFrame({"key": ["foo", "foo2"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo2"], "rval": [4, 5]})

In [114]:
dfab1= left.merge(right,on="key", how='inner')
dfab1

    key  lval  rval
0   foo     1     4
1  foo2     2     5

NameError: name 'emp' is not defined