# **DataFrame 활용**

In [1]:
import numpy as np
import pandas as pd

In [2]:
dept= pd.read_csv("../datas/dept.csv")

In [3]:
dept

   DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [4]:
emp= pd.read_csv("../datas/emp.csv")

In [5]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

# **viewing data**

df.info()
df.shape : 행*열
df.index : 인덱스
df.columns : 컬럼이름
df.head() / df.tail()

In [6]:
dept.info

<bound method DataFrame.info of    DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON>

In [7]:
dept.shape

(4, 3)

In [8]:
dept.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
dept.columns

Index(['DEPTNO', 'DNAME', 'LOC'], dtype='str')

In [10]:
dept.head(1)

   DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK

In [11]:
dept.tail(2)

   DEPTNO       DNAME      LOC
2      30       SALES  CHICAGO
3      40  OPERATIONS   BOSTON

In [12]:
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   EMPNO     14 non-null     int64
 1   ENAME     14 non-null     str
 2   JOB       14 non-null     str
 3   MGR       13 non-null     float64
 4   HIREDATE  14 non-null     str
 5   SAL       14 non-null     int64
 6   COMM      4 non-null      float64
 7   DEPTNO    14 non-null     int64
dtypes: float64(2), int64(3), str(3)
memory usage: 1.0 KB

In [13]:
emp.shape

(14, 8)

In [14]:
emp.index

RangeIndex(start=0, stop=14, step=1)

In [15]:
emp.head(5)

   EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0   7369   SMITH     CLERK  7902.0  17-DEC-80   800     NaN      20
1   7499   ALLEN  SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3   7566   JONES   MANAGER  7839.0  02-APR-81  2975     NaN      20
4   7654  MARTIN  SALESMAN  7698.0  28-SEP-81  1250  1400.0      30

In [16]:
emp.tail(3)

    EMPNO   ENAME      JOB     MGR   HIREDATE   SAL  COMM  DEPTNO
11   7900   JAMES    CLERK  7698.0  03-DEC-81   950   NaN      30
12   7902    FORD  ANALYST  7566.0  03-DEC-81  3000   NaN      20
13   7934  MILLER    CLERK  7782.0  23-JAN-82  1300   NaN      10

In [17]:
emp.columns

Index(['EMPNO', 'ENAME', 'JOB', 'MGR', 'HIREDATE', 'SAL', 'COMM', 'DEPTNO'], dtype='str')

In [18]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [19]:
emp[['EMPNO', 'ENAME']]

    EMPNO   ENAME
0    7369   SMITH
1    7499   ALLEN
2    7521    WARD
3    7566   JONES
4    7654  MARTIN
5    7698   BLAKE
6    7782   CLARK
7    7788   SCOTT
8    7839    KING
9    7844  TURNER
10   7876   ADAMS
11   7900   JAMES
12   7902    FORD
13   7934  MILLER

In [20]:
#emp.iloc[:, 0:2]
emp.iloc[:,[0,1]]

    EMPNO   ENAME
0    7369   SMITH
1    7499   ALLEN
2    7521    WARD
3    7566   JONES
4    7654  MARTIN
5    7698   BLAKE
6    7782   CLARK
7    7788   SCOTT
8    7839    KING
9    7844  TURNER
10   7876   ADAMS
11   7900   JAMES
12   7902    FORD
13   7934  MILLER

In [21]:
emp.loc[:,'EMPNO':'ENAME']

    EMPNO   ENAME
0    7369   SMITH
1    7499   ALLEN
2    7521    WARD
3    7566   JONES
4    7654  MARTIN
5    7698   BLAKE
6    7782   CLARK
7    7788   SCOTT
8    7839    KING
9    7844  TURNER
10   7876   ADAMS
11   7900   JAMES
12   7902    FORD
13   7934  MILLER

In [22]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [23]:
emp.loc[1:3,'JOB':'MGR']

        JOB     MGR
1  SALESMAN  7698.0
2  SALESMAN  7698.0
3   MANAGER  7839.0

In [24]:
emp.iloc[1:4,2:4]

        JOB     MGR
1  SALESMAN  7698.0
2  SALESMAN  7698.0
3   MANAGER  7839.0

In [25]:
emp.loc[:,'COMM':'DEPTNO']

      COMM  DEPTNO
0      NaN      20
1    300.0      30
2    500.0      30
3      NaN      20
4   1400.0      30
5      NaN      30
6      NaN      10
7      NaN      20
8      NaN      10
9      0.0      30
10     NaN      20
11     NaN      30
12     NaN      20
13     NaN      10

In [26]:
emp.iloc[:,[-2,-1]]

      COMM  DEPTNO
0      NaN      20
1    300.0      30
2    500.0      30
3      NaN      20
4   1400.0      30
5      NaN      30
6      NaN      10
7      NaN      20
8      NaN      10
9      0.0      30
10     NaN      20
11     NaN      30
12     NaN      20
13     NaN      10

In [27]:
emp[['ENAME','SAL','DEPTNO']]

     ENAME   SAL  DEPTNO
0    SMITH   800      20
1    ALLEN  1600      30
2     WARD  1250      30
3    JONES  2975      20
4   MARTIN  1250      30
5    BLAKE  2850      30
6    CLARK  2450      10
7    SCOTT  3000      20
8     KING  5000      10
9   TURNER  1500      30
10   ADAMS  1100      20
11   JAMES   950      30
12    FORD  3000      20
13  MILLER  1300      10

In [28]:
emp.iloc[[1,5,12,13],:]
#iloc[[1,5,12,13]]

    EMPNO   ENAME       JOB     MGR   HIREDATE   SAL   COMM  DEPTNO
1    7499   ALLEN  SALESMAN  7698.0  20-FEB-81  1600  300.0      30
5    7698   BLAKE   MANAGER  7839.0  01-MAY-81  2850    NaN      30
12   7902    FORD   ANALYST  7566.0  03-DEC-81  3000    NaN      20
13   7934  MILLER     CLERK  7782.0  23-JAN-82  1300    NaN      10

In [29]:
emp.iloc[[1,5,12,13],:3]
# emp.iloc[[1,5,12,13],[1,2,3]]
#emp.iloc[[1,5,12,13],'EMPNO','ENAME','JOB']

    EMPNO   ENAME       JOB
1    7499   ALLEN  SALESMAN
5    7698   BLAKE   MANAGER
12   7902    FORD   ANALYST
13   7934  MILLER     CLERK

In [30]:
emp.iat[8,1]
#emp.at[8,'ENAME']
#emp.loc[8,'ENAME']
#emp.iloc[8,1]

'KING'

# **Missing data**
* 겅즉 : NaN, null,np.nan
* fillna() : 채우기(보간)
* dropna() : 버리기
* isna() : 결측체크

* 컴럼 별 결축 수

In [31]:
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   EMPNO     14 non-null     int64
 1   ENAME     14 non-null     str
 2   JOB       14 non-null     str
 3   MGR       13 non-null     float64
 4   HIREDATE  14 non-null     str
 5   SAL       14 non-null     int64
 6   COMM      4 non-null      float64
 7   DEPTNO    14 non-null     int64
dtypes: float64(2), int64(3), str(3)
memory usage: 1.0 KB

In [32]:
emp.isna().sum()

EMPNO        0
ENAME        0
JOB          0
MGR          1
HIREDATE     0
SAL          0
COMM        10
DEPTNO       0
dtype: int64

In [33]:
emp['SAL']+emp['COMM']

0        NaN
1     1900.0
2     1750.0
3        NaN
4     2650.0
5        NaN
6        NaN
7        NaN
8        NaN
9     1500.0
10       NaN
11       NaN
12       NaN
13       NaN
dtype: float64

* COMM이 NaN이면 0으로 보간

In [34]:
emp['COMM'] = emp['COMM'].fillna(0)

In [35]:
emp['SAL'] + emp['COMM']

0      800.0
1     1900.0
2     1750.0
3     2975.0
4     2650.0
5     2850.0
6     2450.0
7     3000.0
8     5000.0
9     1500.0
10    1100.0
11     950.0
12    3000.0
13    1300.0
dtype: float64

In [36]:
emp2 = emp.dropna()
emp2

    EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH     CLERK  7902.0  17-DEC-80   800     0.0      20
1    7499   ALLEN  SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD  SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES   MANAGER  7839.0  02-APR-81  2975     0.0      20
4    7654  MARTIN  SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE   MANAGER  7839.0  01-MAY-81  2850     0.0      30
6    7782   CLARK   MANAGER  7839.0  09-JUN-81  2450     0.0      10
7    7788   SCOTT   ANALYST  7566.0  19-APR-87  3000     0.0      20
9    7844  TURNER  SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS     CLERK  7788.0  23-MAY-87  1100     0.0      20
11   7900   JAMES     CLERK  7698.0  03-DEC-81   950     0.0      30
12   7902    FORD   ANALYST  7566.0  03-DEC-81  3000     0.0      20
13   7934  MILLER     CLERK  7782.0  23-JAN-82  1300     0.0      10

* <b>emp에 연봉컬럼(YSAL) 추가하기
* YSAL = SAL*12 + COMM

In [37]:
emp['YSAL'] = emp['SAL']*12 + emp['COMM']
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO     YSAL
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     0.0      20   9600.0
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30  19500.0
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30  15500.0
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     0.0      20  35700.0
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30  16400.0
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     0.0      30  34200.0
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     0.0      10  29400.0
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     0.0      20  36000.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     0.0      10  60000.0
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30  18000.0
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     0.0      20  13200.0
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     0.0      30  11400.0
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     0.0      20  36000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     0.0      10  15600.0

# **결측 삭제**
* df.dropna(axis=0) : 행(줄,가로,↓)지우기
* df.dropna(axis=1) : 열(칸,세로,→)지우기
* df.dropna(subset=['컬럼']) : 컬럼에 결측 지우기
* df.drop(columns=['컬럼']) : 컬럼 삭제

In [38]:
emp22= pd.read_csv("../datas/emp.csv")

In [39]:
emp22

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [40]:
emp22 = emp22.dropna(subset=['COMM'])

In [41]:
emp22

   EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0  22-FEB-81  1250   500.0      30
4   7654  MARTIN  SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
9   7844  TURNER  SALESMAN  7698.0  08-SEP-81  1500     0.0      30

In [42]:
emp22 = emp22.drop(columns= ['JOB','MGR'])
emp22

   EMPNO   ENAME   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  20-FEB-81  1600   300.0      30
2   7521    WARD  22-FEB-81  1250   500.0      30
4   7654  MARTIN  28-SEP-81  1250  1400.0      30
9   7844  TURNER  08-SEP-81  1500     0.0      30

In [43]:
emp22

   EMPNO   ENAME   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  20-FEB-81  1600   300.0      30
2   7521    WARD  22-FEB-81  1250   500.0      30
4   7654  MARTIN  28-SEP-81  1250  1400.0      30
9   7844  TURNER  08-SEP-81  1500     0.0      30

In [44]:
emp22 = emp22.dropna(subset=['COMM'])

In [45]:
emp22

   EMPNO   ENAME   HIREDATE   SAL    COMM  DEPTNO
1   7499   ALLEN  20-FEB-81  1600   300.0      30
2   7521    WARD  22-FEB-81  1250   500.0      30
4   7654  MARTIN  28-SEP-81  1250  1400.0      30
9   7844  TURNER  08-SEP-81  1500     0.0      30

In [46]:
emp22= pd.read_csv("../datas/emp.csv")
emp22

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [47]:
emp22 = emp22.drop(columns= ['JOB','MGR'])
emp22

    EMPNO   ENAME   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH  17-DEC-80   800     NaN      20
1    7499   ALLEN  20-FEB-81  1600   300.0      30
2    7521    WARD  22-FEB-81  1250   500.0      30
3    7566   JONES  02-APR-81  2975     NaN      20
4    7654  MARTIN  28-SEP-81  1250  1400.0      30
5    7698   BLAKE  01-MAY-81  2850     NaN      30
6    7782   CLARK  09-JUN-81  2450     NaN      10
7    7788   SCOTT  19-APR-87  3000     NaN      20
8    7839    KING  17-NOV-81  5000     NaN      10
9    7844  TURNER  08-SEP-81  1500     0.0      30
10   7876   ADAMS  23-MAY-87  1100     NaN      20
11   7900   JAMES  03-DEC-81   950     NaN      30
12   7902    FORD  03-DEC-81  3000     NaN      20
13   7934  MILLER  23-JAN-82  1300     NaN      10

# **stat.**

In [48]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO     YSAL
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     0.0      20   9600.0
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30  19500.0
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30  15500.0
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     0.0      20  35700.0
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30  16400.0
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     0.0      30  34200.0
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     0.0      10  29400.0
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     0.0      20  36000.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     0.0      10  60000.0
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30  18000.0
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     0.0      20  13200.0
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     0.0      30  11400.0
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     0.0      20  36000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     0.0      10  15600.0

* <font color=red><b>★★JOB별 사원수|

In [49]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO     YSAL
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     0.0      20   9600.0
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30  19500.0
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30  15500.0
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     0.0      20  35700.0
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30  16400.0
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     0.0      30  34200.0
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     0.0      10  29400.0
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     0.0      20  36000.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     0.0      10  60000.0
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30  18000.0
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     0.0      20  13200.0
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     0.0      30  11400.0
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     0.0      20  36000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     0.0      10  15600.0

In [50]:
emp.groupby("JOB")["EMPNO"].count()
emp['JOB'].value_counts()

JOB
CLERK        4
SALESMAN     4
MANAGER      3
ANALYST      2
PRESIDENT    1
Name: count, dtype: int64

In [51]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO     YSAL
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     0.0      20   9600.0
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30  19500.0
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30  15500.0
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     0.0      20  35700.0
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30  16400.0
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     0.0      30  34200.0
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     0.0      10  29400.0
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     0.0      20  36000.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     0.0      10  60000.0
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30  18000.0
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     0.0      20  13200.0
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     0.0      30  11400.0
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     0.0      20  36000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     0.0      10  15600.0

* <font color=red><b>★★각 부서(DEPTNO)별 JOB별 급여(SAL) 총합

In [52]:
emp.groupby(['DEPTNO','JOB'])['SAL'].sum()

DEPTNO  JOB
10      CLERK        1300
        MANAGER      2450
        PRESIDENT    5000
20      ANALYST      6000
        CLERK        1900
        MANAGER      2975
30      CLERK         950
        MANAGER      2850
        SALESMAN     5600
Name: SAL, dtype: int64

* <font color=red><b>★★부서(DEPTNO)별 급여(SAL) 최소 / 최대

In [53]:
emp.groupby("DEPTNO")["SAL"].agg(['min','max']).reset_index()

   DEPTNO   min   max
0      10  1300  5000
1      20   800  3000
2      30   950  2850

In [54]:
emp.groupby(['DEPTNO','JOB'])['SAL'].sum().reset_index()

   DEPTNO        JOB   SAL
0      10      CLERK  1300
1      10    MANAGER  2450
2      10  PRESIDENT  5000
3      20    ANALYST  6000
4      20      CLERK  1900
5      20    MANAGER  2975
6      30      CLERK   950
7      30    MANAGER  2850
8      30   SALESMAN  5600

* <font color=red><b>★★부서(DEPTNO)별 급여(SAL) 최소 / 입사일(HIREDATE)최대

In [55]:
emp.groupby("DEPTNO").agg({"SAL" :"min", "HIREDATE":"max"}).reset_index()

   DEPTNO   SAL   HIREDATE
0      10  1300  23-JAN-82
1      20   800  23-MAY-87
2      30   950  28-SEP-81

# **merge vs. concat**

* emp dept merge

In [56]:
dept

   DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [57]:
emp.merge(dept,on='DEPTNO', how='inner')

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,YSAL,DNAME,LOC
0,7369,SMITH,CLERK,7902.0,17-DEC-80,800,0.0,20,9600.0,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698.0,20-FEB-81,1600,300.0,30,19500.0,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698.0,22-FEB-81,1250,500.0,30,15500.0,SALES,CHICAGO
3,7566,JONES,MANAGER,7839.0,02-APR-81,2975,0.0,20,35700.0,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,28-SEP-81,1250,1400.0,30,16400.0,SALES,CHICAGO
5,7698,BLAKE,MANAGER,7839.0,01-MAY-81,2850,0.0,30,34200.0,SALES,CHICAGO
6,7782,CLARK,MANAGER,7839.0,09-JUN-81,2450,0.0,10,29400.0,ACCOUNTING,NEW YORK
7,7788,SCOTT,ANALYST,7566.0,19-APR-87,3000,0.0,20,36000.0,RESEARCH,DALLAS
8,7839,KING,PRESIDENT,NaN,17-NOV-81,5000,0.0,10,60000.0,ACCOUNTING,NEW YORK
9,7844,TURNER,SALESMAN,7698.0,08-SEP-81,1500,0.0,30,18000.0,SALES,CHICAGO
10,7876,ADAMS,CLERK,7788.0,23-MAY-87,1100,0.0,20,13200.0,RESEARCH,DALLAS
11,7900,JAMES,CLERK,7698.0,03-DEC-81,950,0.0,30,11400.0,SALES,CHICAGO
12,7902,FORD,ANALYST,7566.0,03-DEC-81,3000,0.0,20,36000.0,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782.0,23-JAN-82,1300,0.0,10,15600.0,ACCOUNTING,NEW YORK

# **필터링**
* <font color=red><b> [ (조건절) & | (조건절) ]
* emp [조건절][컬럼]
* emp [컬럼][조건절]

In [58]:
#emp['DEPTNO'] == 30
#emp[emp['DEPTNO'] == 30]

In [59]:
emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO     YSAL
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     0.0      20   9600.0
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30  19500.0
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30  15500.0
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     0.0      20  35700.0
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30  16400.0
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     0.0      30  34200.0
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     0.0      10  29400.0
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     0.0      20  36000.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     0.0      10  60000.0
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30  18000.0
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     0.0      20  13200.0
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     0.0      30  11400.0
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     0.0      20  36000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     0.0      10  15600.0

In [60]:
 emp[emp['DEPTNO'] ==30][['EMPNO', 'ENAME', 'DEPTNO']]

    EMPNO   ENAME  DEPTNO
1    7499   ALLEN      30
2    7521    WARD      30
4    7654  MARTIN      30
5    7698   BLAKE      30
9    7844  TURNER      30
11   7900   JAMES      30

In [61]:
emp [(emp['DEPTNO'] == 20) | (emp['DEPTNO']== 30)]
emp [ emp['DEPTNO'].isin([20,30])]

    EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO     YSAL
0    7369   SMITH     CLERK  7902.0  17-DEC-80   800     0.0      20   9600.0
1    7499   ALLEN  SALESMAN  7698.0  20-FEB-81  1600   300.0      30  19500.0
2    7521    WARD  SALESMAN  7698.0  22-FEB-81  1250   500.0      30  15500.0
3    7566   JONES   MANAGER  7839.0  02-APR-81  2975     0.0      20  35700.0
4    7654  MARTIN  SALESMAN  7698.0  28-SEP-81  1250  1400.0      30  16400.0
5    7698   BLAKE   MANAGER  7839.0  01-MAY-81  2850     0.0      30  34200.0
7    7788   SCOTT   ANALYST  7566.0  19-APR-87  3000     0.0      20  36000.0
9    7844  TURNER  SALESMAN  7698.0  08-SEP-81  1500     0.0      30  18000.0
10   7876   ADAMS     CLERK  7788.0  23-MAY-87  1100     0.0      20  13200.0
11   7900   JAMES     CLERK  7698.0  03-DEC-81   950     0.0      30  11400.0
12   7902    FORD   ANALYST  7566.0  03-DEC-81  3000     0.0      20  36000.0

In [62]:
emp [~ (emp['DEPTNO'].isin( [20,30]))]

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL  COMM  DEPTNO     YSAL
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450   0.0      10  29400.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000   0.0      10  60000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300   0.0      10  15600.0

* <b>DEPTNO가 10인 사원 출력

In [63]:
emp[emp['DEPTNO'] == 10]

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL  COMM  DEPTNO     YSAL
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450   0.0      10  29400.0
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000   0.0      10  60000.0
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300   0.0      10  15600.0

* <b>DEPTNO가 10이고 급여가 2000이상 사원  출력

In [64]:
emp[(emp['DEPTNO'] == 10) & (emp['SAL'] >= 2000)]

   EMPNO  ENAME        JOB     MGR   HIREDATE   SAL  COMM  DEPTNO     YSAL
6   7782  CLARK    MANAGER  7839.0  09-JUN-81  2450   0.0      10  29400.0
8   7839   KING  PRESIDENT     NaN  17-NOV-81  5000   0.0      10  60000.0

* <b>DEPTNO가 10이고 급여가 2000이상 사원의 EMPNO, ENAME, SAL, DEPTNO 출력

In [65]:
emp[(emp['DEPTNO'] == 10) & (emp['SAL'] >= 2000)] [['EMPNO', 'ENAME','SAL', 'DEPTNO']]

   EMPNO  ENAME   SAL  DEPTNO
6   7782  CLARK  2450      10
8   7839   KING  5000      10