# **컨프리헨션 & 람다**

* <b>for문 1~10 짝수만 출력

In [1]:
for v in range(1,11):
    if(v%2==0):
        print(v, end = ' ')

2 4 6 8 10

In [2]:
[v for v in range(1,11) if (v%2==0) ]

[2, 4, 6, 8, 10]

In [ ]:
* <b>for문 1~5 3보다크면 값

In [7]:
[v*2  if(v>3) else v for v in range(1,6)]

[1, 2, 3, 8, 10]

In [4]:
for v in range (1,6):
    if v>3:
        print(v*2, end=' ')
    else:
        print(v, end= ' ')

1 2 3 8 10

# **람다(lambda)**
* 익명(이름없는) 함수
* 1회용

* 함수이름 : add
* 파라미터 : 숫자2개 
* 합산 결과 리턴

* 람다 예제

In [10]:
def add(a,b):
    res= a + b
    return res
m= add(3,5)
print(m)

8

In [15]:
add2= lambda a, b : a+b
add2(3,5)

8

In [11]:
def ncheck(n):
    print(n*2)
ncheck(6)

12

In [13]:
myf = lambda n :n*2

In [14]:
myf(6)

12

In [17]:
a = lambda n : n if n > 10 else None
a(20)

20

* <b> 람다 예정

In [ ]:
def add(n1):
    res= n1 + 
    return res

In [ ]:
a= lambda n1 : check()

# **DataFrame을 활용한 lambda**

In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.DataFrame({
    "name": ["kim", "hong", "park"],
    "age": [20, 25, 30]
})
df

   name  age
0   kim   20
1  hong   25
2  park   30

In [21]:
df['age'] = df['age'] + 10
df

   name  age
0   kim   30
1  hong   35
2  park   40

In [22]:
df['age']= df['age'].apply(lambda a : a+10)
df

   name  age
0   kim   40
1  hong   45
2  park   50

In [23]:
df['etc']= df['age'].apply(lambda a : '성인'if a>=20 else '미성인' )
df

   name  age etc
0   kim   40  성인
1  hong   45  성인
2  park   50  성인