In [5]:
import pandas as pd

In [6]:
import ssl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# HTTPS 인증서 오류 우회
ssl._create_default_https_context = ssl._create_unverified_context

# 차트 관련 속성
# 한글 처리
plt.rcParams['font.family'] = 'Malgun Gothic'

# 마이너스 기호 처리
plt.rcParams['axes.unicode_minus'] = False

In [17]:
dfa = pd.DataFrame({"id" : [1,2,3] , "name":["Lan","Linh","Mai"]})
dfb = pd.DataFrame({"id" : [1,2,3] , "age":[40,25,50]})

In [18]:
dfa

   id  name
0   1   Lan
1   2  Linh
2   3   Mai

In [19]:
dfb

   id  age
0   1   40
1   2   25
2   3   50

In [15]:
dfa.merge(dfb, on='id')

   id  name  age
0   1   Lan   40
1   2  Linh   25
2   3   Mai   50

In [20]:
dfa = pd.DataFrame({"id" : [1,2,3] , "name":["Lan","Linh","Mai"]})
dfb = pd.DataFrame({"id" : [4,5] , "name":["Minh","Na"]})

In [21]:
dfa

   id  name
0   1   Lan
1   2  Linh
2   3   Mai

In [9]:
aa = pd.DataFrame({"A":[1,2,3,4,5,6],"B":[1,2,3,4,5,6]})
#aa = aa.drop(columns=["A"])
#aa = aa.drop([1,2,3], axis=0)
#aa = aa.drop(['A'], axis=1)
aa= aa.drop([''])
aa

   B
0  1
1  2
2  3
3  4
4  5
5  6

In [28]:
dfab = pd.concat([dfa,dfb],axis=0)
dfab

dfab

   id  name
0   1   Lan
1   2  Linh
2   3   Mai
0   4  Minh
1   5    Na

In [30]:
dfab = pd.concat([dfa,dfb],axis=1)
dfab

   id  name   id  name
0   1   Lan  4.0  Minh
1   2  Linh  5.0    Na
2   3   Mai  NaN   NaN

In [ ]:
emp[["ENAME","SAL"]]    [()]

In [ ]:
emp[[ㅋ]][(ㅈ)]

In [ ]:
[(emp["SAL"]> 2000) & (emp["SAL"]== 2000)]

# **ML**

In [ ]:
from sklearn import set_config
set_config(display="text")

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dept= pd.read_csv("../datas/dept.csv")

In [ ]:
df.columns = df.columns.str.upper()

In [ ]:
X = df.drop(columns=["MEDV"])
X.head(2)

In [ ]:
X = df.drop(columns=["MEDV"])
X.head(2)

In [ ]:
y = df['MEDV']
y.head(2)

In [ ]:
from sklearn.model_selection import train_test_split
X_train7, X_test3,    y_train7, y_test3 = train_test_split( X, y, test_size=0.3, random_state=1234)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr.fit(X_train7, y_train7)

In [ ]:
pred = lr.predict(X_test3)
pred[:10]

In [ ]:
y_test3[:10]

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test3, pred)
print( np.sqrt(mse) )

In [ ]:
# ==========================================
# [추가] 파생 피처 생성 (train과 test 양쪽에 모두 적용)
# ==========================================
# 1. 비만도(bmi)와 나이(age)를 조합한 파생 피처 생성
train['bmi_age_ratio'] = train['bmi'] / train['age']
test['bmi_age_ratio'] = test['bmi'] / test['age']
# 2. 포도당(glucose)과 인슐린(insulin) 비율 파생 피처 생성 (분모 0 방지 +1)
train['glucose_insulin_ratio'] = train['glucose'] / (train['insulin'] + 1)
test['glucose_insulin_ratio'] = test['glucose'] / (test['insulin'] + 1)
print('파생 피처 생성 완료! 현재 train 컬럼 개수:', train.shape[1])
print('현재 test 컬럼 개수:', test.shape[1])